name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  my_build_job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: nmp install, test and build
        run: |
          npm install
          npm run build
      - name: Run a one-line script
        run: echo Hello, World!
      - name: run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project


      - name: Run JS file for test
        run: node js.js
